### PR TITLE
Add start script to seed while playing

### PR DESCRIPTION
**Pull request by ouzu**
This adds a start script which seeds the model torrent in background (addressing #87 )

### CODE REVIEW

**Comment by ben-bay** [comment]
@ouzu it looks like there's a conflict here

**Comment by nickwalton** [comment]
I'm also nervous about this. Not sure how Google would feel about us using not just their compute bit also heir bandwidth

**Comment by Renha** [comment]
Then use the script on own hardware

**Comment by ouzu** [comment]
@ben-bay I will resolve the conflicts with the new scripts.

@nickwalton I haven't changed the notebook, so it doesn't affect the colab environment without further changes.

**Comment by Gol-D-Ace** [comment]
I tried seeding from colab and it doesn't really seem to get to any decent speed. Maybe they limit upload bandwidth.

**Pull request closed without merging**
